### ISSUE TITLE
People images not visible on mobile

### ISSUE THREAD

**Issue by AmbroiseCollon** [MeetMangrove/mangrove-website#25]
Tested on iOS Safari, people pictures on mangrove.io/team are not visible. But it works on Safari, Chrome and Firefox desktop (even when size is reduced to mobile size). Couldn't test it on Androïd.

**Comment by tjeanneau** [comment]
We can't use twitter pictures because it's not working on mobile: https://support.twitter.com/articles/20169452

**Comment by tjeanneau** [comment]
Done with Airtable ;)
